dist: xenial
language: node_js
node_js:
  - '10.15'
services:
  - docker
install:
  - cp .env.example .env
script:
  - docker build -t cars-club:test -f dockerfiles/Test.Dockerfile .
  - docker run cars-club:test
deploy:
  provider: heroku
  api_key:
    master: 92e401a3-7be6-4850-bbdd-ff4a22e29e74
    develop: 92e401a3-7be6-4850-bbdd-ff4a22e29e74
  app:
    master: cars-club
    develop: dev-cars-club
