dist: xenial
language: node_js
node_js:
  - '10.15'
services:
  - docker
install:
  - cp .env.example .env
script:
  - docker build -t cars-club:test -f dockerfiles/Test.Dockerfile .
  - docker run cars-club:test